credentials:
  usernames:
    seanguo:
      email: seanguo@amazon.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: True # Will be managed automatically
      name: Sean Guo
      password: $2b$12$3kVpdhhx/4Je.G0SPd4kgeSuxDiZOY0qlI4yBtwDAYDti1RtnWUYO
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - melsby@gmail.com